baseURL = "https://50335033.xyz/"
locale = "en-us"
title = "Red Earth"
theme = "hugo-theme-console"

[params]
description = "Red Earth's homepage"
animateStyle = "animate-fade-up"

[[params.navlinks]]
name = "About"
url = "/about/"

[[params.navlinks]]
name = "Posts"
url = "/posts/"

[[params.navlinks]]
name = "Photos"
url = "/photos/"
